# Generated by Django 3.2.9 on 2022-08-22 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lwlife', '0003_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
