# Generated by Django 3.2.9 on 2022-08-24 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lwlife', '0006_auto_20220824_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='ques_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
